Vagrant.configure("2") do |config|
    config.vm.define "cyberquest1" do |cfg|
      cfg.vm.box = "generic/ubuntu1804"
      cfg.vm.hostname = "rocket"
      cfg.vm.network :private_network, ip: "99.99.99.99", gateway: "99.99.99.0", dns: "99.99.99.0"
      cfg.vm.synced_folder "data", "/shared"
      cfg.vm.synced_folder "scripts", "/scripts"
      cfg.vm.provision "shell", path: "scripts/scenario.sh"

      cfg.vm.provider "virtualbox" do |vb, override|
        vb.gui = true
        vb.customize ["modifyvm", :id, "--memory", 4096]
        vb.customize ["modifyvm", :id, "--cpus", 2]
        vb.customize ["modifyvm", :id, "--vram", "32"]
        vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
        vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
      end
    end
  end
  